### ISSUE TITLE
In  scripts/convert_weights, when the source file is a .caffefile, it converted to  a vgg-based pytorch network, this is why? why the BACKEND_NETWORK must be vgg?

### ISSUE THREAD

**Issue by ShiAngWang** [Time0o/pytorch-colorful-colorization#44]

**Comment by Time0o** [comment]
The `convert_weights` script essentially exists to convert both pretrained weights provided by the authors of the original colorful colorization paper and pretrained weights for Google's Deepv3+ (an alternative backend, which I never really got around to testing) into a PyTorch format in order to use them with this implementation.

Because Zhang et. al. implemented their (vgg-based) network in caffe, the input to `convert_weights` should be one of their caffe models downloaded by `resources/get_resources.sh`. If the resulting PyTorch weights are then used with this network it should perform identically to the network described in the paper.

**Comment by ShiAngWang** [comment]
> The `convert_weights` script essentially exists to convert both pretrained weights provided by the authors of the original colorful colorization paper and pretrained weights for Google's Deepv3+ (an alternative backend, which I never really got around to testing) into a PyTorch format in order to use them with this implementation.
> 
> Because Zhang et. al. implemented their (vgg-based) network in caffe, the input to `convert_weights` should be one of their caffe models downloaded by `resources/get_resources.sh`. If the resulting PyTorch weights are then used with this network it should perform identically to the network described in the paper.

Thank you very much for your reply! So  the structure of the vgg-based pytorch model in your implementation is same with the original caffe model of Zhang's, is it right?

**Comment by Time0o** [comment]
Yes, it is intended to be an identical reimplementation.

**Comment by ShiAngWang** [comment]
Thank you^_^
